### ISSUE TITLE
splitarg doesn't recognize keyword arguments after semicolon

### ISSUE THREAD

**Issue by piever** [MikeInnes/MacroTools.jl#53] opened 2017-09-06 15:56 UTC
I don't know if it is intended, but `splitarg` errors if there are keyword arguments after the `;`, it'd be very useful if it could also recognize those (just like `splitdef`does):

```julia
julia> map(splitarg, (:(f(a=2, x::Int=nothing, y; z = 12))).args[2:end])
ERROR: TypeError: splitvar: in typeassert, expected Symbol, got Expr
Stacktrace:
 [1] macro expansion at /Users/pietro/.julia/v0.6/MacroTools/src/utils.jl:287 [inlined]
 [2] macro expansion at /Users/pietro/.julia/v0.6/MacroTools/src/macro.jl:14 [inlined]
 [3] (::MacroTools.#splitvar#28)(::Expr) at /Users/pietro/.julia/v0.6/MacroTools/src/utils.jl:283
 [4] splitarg(::Expr) at /Users/pietro/.julia/v0.6/MacroTools/src/utils.jl:294
 [5] _collect(::Array{Any,1}, ::Base.Generator{Array{Any,1},MacroTools.#splitarg}, ::Base.EltypeUnknown, ::Base.HasShape) at ./array.jl:454
 [6] map(::Function, ::Array{Any,1}) at ./abstractarray.jl:1865
```

**Comment by cstjean** [comment] 2017-09-06 19:01
The problem is that the the first element contains all the kwargs.

```julia
julia> :(f(a=2, x::Int=nothing, y; z = 12, w=13)).args[2:end]
4-element Array{Any,1}:
 :($(Expr(:parameters, :(z=12), :(w=13))))
 :(a=2)                                   
 :(x::Int=nothing)                        
 :y  
```

Normal usage is

```julia
julia> @capture :(f(a=2, x::Int=nothing, y; z = 12, w=13)) fun_(args__; kwargs__)
true

julia> map(splitarg, (args..., kwargs...))
((:a, :Any, false, 2), (:x, :Int, false, :nothing), (:y, :Any, false, nothing), (:z, :Any, false, 12), (:w, :Any, false, 13))
```

**Comment by cstjean** [comment] 2017-09-06 19:18
Oops, didn't realize your example came from the README, I should fix that!

**Comment by piever** [comment] 2017-09-06 22:41
I actually figured out there was `@capture :(f(a=2, x::Int=nothing, y; z = 12, w=13)) fun_(args__; kwargs__)` after posting the issue and felt a bit silly. But it's true that it could be made a bit more obvious from the README.
Thanks for the fast reply and congratulations on this package: at least for my use case of decomposing function calls it really is much nicer than dealing with expressions by hand.

**Comment by cstjean** [comment] 2018-04-25 12:07
That was fixed in https://github.com/MikeInnes/MacroTools.jl/commit/dae1c9e0e8739a26040f61dcdbfabfd6be540112

**Closed** 2018-04-25 12:08 UTC
